# Generated by Django 4.1.4 on 2023-02-06 21:40

import accounts.models
import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_type', models.CharField(default='normal', max_length=20)),
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Account number must be a number')])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_balance', models.DecimalField(decimal_places=2, default=Decimal('9999999.00'), max_digits=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer')], max_length=10)),
                ('payment_method', models.CharField(default='internal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(default=accounts.models.generate_reference_number, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_transactions', related_query_name='beneficiary_transaction', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', related_query_name='customer_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
