# Generated by Django 4.1.4 on 2023-01-05 13:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='normal', max_length=20)),
                ('account_number', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Account number must be a number')])),
                ('balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('transaction_history', models.JSONField(blank=True, null=True)),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='active', max_length=20)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=40, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_methods', models.JSONField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
