# Generated by Django 4.1.7 on 2023-03-20 06:07

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 6, 7, 4, 73483, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
