# Generated by Django 4.1.7 on 2023-03-20 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_max_balance_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 10, 20, 22, 750980, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
