# Generated by Django 4.1.7 on 2023-03-20 10:31

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 10, 31, 56, 567585, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='max_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='min_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), editable=False, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
