# Generated by Django 4.1.4 on 2023-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('cc', models.EmailField(blank=True, max_length=254)),
                ('bcc', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('draft', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, upload_to='attachments')),
            ],
        ),
    ]
