# Generated by Django 4.1.7 on 2023-02-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='references',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
