# Generated by Django 4.1.7 on 2023-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_resume_contact_info_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
