# Generated by Django 4.1.7 on 2023-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_resume_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cover_letter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
