# Generated by Django 4.1.7 on 2023-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_resume_contact_info_alter_resume_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
