# Generated by Django 4.1.7 on 2023-03-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_resume_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessplan',
            old_name='management_team',
            new_name='swot_analysis',
        ),
    ]
