# Generated by Django 4.1.7 on 2023-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rename_management_team_businessplan_swot_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
