# Generated by Django 4.1.7 on 2023-03-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename__email_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_last_name',
            new_name='last_name',
        ),
    ]
