# Generated by Django 4.1.4 on 2023-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_chatcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiration_date', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatCompletion',
        ),
    ]
