# Generated by Django 4.1.4 on 2023-02-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('database', 'Database')], default='email', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('to', models.TextField()),
            ],
        ),
    ]
